[theme]
background = "#282a36"
primary = "#F8F8F2"
secondary = "light black"
title = "#bd93f9"
playing = "#bd93f9"
playing_selected = "#D0B3FA"
playing_bg = "#282a36"
highlight = "#f8f8f2"
highlight_bg = "#44475a"
error = "#f8f8f2"
error_bg = "#ff5555"
statusbar = "black"
statusbar_progress = "#bd93f9"
statusbar_bg = "#bd93f9"
cmdline = "#f8f8f2"
cmdline_bg = "#282a36"
search_match = "#ff79c6"

[keybindings]
"Ctrl+u" = "move up 20"
"Ctrl+d" = "move down 20"
"Space"  = "playpause"
"Ctrl+l" = "focus library"
"Ctrl+f" = "focus search"
