name: "Test Darwin"
on:
  pull_request:
  push:
    paths:
      - "configuration.nix"
      - "cachix/**"
      - "home/**"
      - "platforms/darwin/**"
      - "machines/mbp16/**"

jobs:
  test-mbp16:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: darwin-config=/Users/runner/work/nix-config/nix-config/configuration.nix:/Users/runner/.nix-defexpr/channels:nixpkgs=channel:nixpkgs-unstable
    - uses: cachix/cachix-action@v10
      with:
        name: yevhenshymotiuk
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - name: Add nixpkgs channel
      run: nix-channel --add https://github.com/yevhenshymotiuk/nixpkgs/archive/nixpkgs-unstable.tar.gz nixpkgs
    - name: Add darwin channel
      run: nix-channel --add https://github.com/LnL7/nix-darwin/archive/master.tar.gz darwin
    - name: Add home-manager channel
      run: nix-channel --add https://github.com/rycee/home-manager/archive/master.tar.gz home-manager
    - name: Update channels
      run: nix-channel --update
    - name: Link host machine config
      run: ln -s ./machines/mbp16 host.nix
    - name: Replace config path
      run: |
        sed -i "" -- \
          "s/darwinConfig = \"\$HOME\/.nixpkgs\/configuration.nix\"/darwinConfig = \"\$HOME\/work\/nix-config\/nix-config\/configuration.nix\"/g" \
          ./platforms/darwin/default.nix
    - name: Disable some packages
      run: |
        sed -i "" \
          -e "/\s*cachix\s*$/d" \
          -e "/\s*Spotify\s*$/d" \
          ./platforms/darwin/home/packages.nix
    - name: Replace username
      run: find . -type f -path "*.nix" -exec sed -i "" -- "s/yevhenshymotiuk/runner/g" {} +
    - name: Install nix-darwin
      run: ./platforms/darwin/nix-darwin-install.sh
